spring:
  datasource:
    url: jdbc:sqlserver://lakshya.database.windows.net:1433;database=myfirstproject;user=lakshya@lakshya;password=laks@5500;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: lakshya 
    password: laks@5500
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
      
     
server:
  port: 9090